{"name": "test_table_manufacturer", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.InternalError: Unread result found", "trace": "db_connection = <mysql.connector.connection_cext.CMySQLConnection object at 0x1023f2df0>\n\n    def test_table_manufacturer(db_connection):\n        with db_connection.cursor() as cursor:\n            with allure.step('INSERT в таблицу Manufacturer'):\n                cursor.execute('INSERT INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)')\n                db_connection.commit()\n                assert cursor.fetchone() is None\n    \n            with allure.step('Проверка результата INSERT'):\n                cursor.execute('SELECT * from manufacturer where name_manufacturer = %s', ('Apple',))\n                assert cursor.fetchone() is not None\n    \n            with allure.step('UPDATE в таблице Manufacturer'):\n>               cursor.execute('UPDATE manufacturer SET country_id = %s WHERE name_manufacturer = %s', (2, 'Apple'))\n\ntest_db.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py:303: in execute\n    self._cnx.handle_unread_result()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mysql.connector.connection_cext.CMySQLConnection object at 0x1023f2df0>, prepared = False\n\n    def handle_unread_result(self, prepared: bool = False) -> None:\n        \"\"\"Check whether there is an unread result\"\"\"\n        unread_result = self._unread_result if prepared is True else self.unread_result\n        if self.can_consume_results:\n            self.consume_results()\n        elif unread_result:\n>           raise InternalError(\"Unread result found\")\nE           mysql.connector.errors.InternalError: Unread result found\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:961: InternalError\n\nDuring handling of the above exception, another exception occurred:\n\ndb_connection = <mysql.connector.connection_cext.CMySQLConnection object at 0x1023f2df0>\n\n    def test_table_manufacturer(db_connection):\n        with db_connection.cursor() as cursor:\n            with allure.step('INSERT в таблицу Manufacturer'):\n                cursor.execute('INSERT INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)')\n                db_connection.commit()\n                assert cursor.fetchone() is None\n    \n            with allure.step('Проверка результата INSERT'):\n                cursor.execute('SELECT * from manufacturer where name_manufacturer = %s', ('Apple',))\n                assert cursor.fetchone() is not None\n    \n            with allure.step('UPDATE в таблице Manufacturer'):\n                cursor.execute('UPDATE manufacturer SET country_id = %s WHERE name_manufacturer = %s', (2, 'Apple'))\n                db_connection.commit()\n                assert cursor.fetchone() is None\n    \n            with allure.step(\"Проверка результата UPDATE в таблице Manufacturer\"):\n                cursor.execute('SELECT country_id from manufacturer where name_manufacturer = %s', ('Apple',))\n                assert cursor.fetchone() == 2\n    \n            with allure.step('DELETE из таблицы Manufacturer'):\n                cursor.execute('DELETE from manufacturer where name_manufacturer = %s', ('Apple',))\n                db_connection.commit()\n    \n            with allure.step(\"Проверка результата DELETE в таблице Manufacturer\"):\n                cursor.execute('SELECT * from manufacturer where name_manufacturer = %s', ('Apple',))\n>               assert cursor.fetchone() is None\n\ntest_db.py:54: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/abstracts.py:1621: in __exit__\n    self.close()\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py:495: in close\n    self._cnx.handle_unread_result()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mysql.connector.connection_cext.CMySQLConnection object at 0x1023f2df0>, prepared = False\n\n    def handle_unread_result(self, prepared: bool = False) -> None:\n        \"\"\"Check whether there is an unread result\"\"\"\n        unread_result = self._unread_result if prepared is True else self.unread_result\n        if self.can_consume_results:\n            self.consume_results()\n        elif unread_result:\n>           raise InternalError(\"Unread result found\")\nE           mysql.connector.errors.InternalError: Unread result found\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:961: InternalError"}, "steps": [{"name": "INSERT в таблицу Manufacturer", "status": "passed", "start": 1698417189873, "stop": 1698417189875}, {"name": "Проверка результата INSERT", "status": "passed", "start": 1698417189875, "stop": 1698417189875}, {"name": "UPDATE в таблице Manufacturer", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.InternalError: Unread result found\n", "trace": "  File \"/Users/akopotov/Documents/College/Testing/checkpoint_6_dB_test/test_db.py\", line 40, in test_table_manufacturer\n    cursor.execute('UPDATE manufacturer SET country_id = %s WHERE name_manufacturer = %s', (2, 'Apple'))\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py\", line 303, in execute\n    self._cnx.handle_unread_result()\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py\", line 961, in handle_unread_result\n    raise InternalError(\"Unread result found\")\n"}, "start": 1698417189875, "stop": 1698417189875}], "start": 1698417189873, "stop": 1698417189878, "uuid": "e782abae-5a42-4adf-a50f-22b80e5ca447", "historyId": "7602d2145fb47dfe4ec3e603a1f4ee46", "testCaseId": "7602d2145fb47dfe4ec3e603a1f4ee46", "fullName": "test_db#test_table_manufacturer", "labels": [{"name": "suite", "value": "test_db"}, {"name": "host", "value": "alexMBP-14.local"}, {"name": "thread", "value": "45353-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_db"}]}