{"name": "test_insert_manufacturer", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.InternalError: Unread result found", "trace": "db_connection = <mysql.connector.connection_cext.CMySQLConnection object at 0x1047739d0>\n\n    def test_insert_manufacturer(db_connection):\n        with db_connection.cursor() as cursor:\n            with allure.step('Insert запрос в таблицу Manufacturer'):\n                cursor.execute('INSERT INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)')\n                db_connection.commit()\n                assert cursor.fetchone() is None\n    \n            with allure.step('Проверка добавления'):\n                cursor.execute('SELECT * from manufacturer where name_manufacturer = %s', ('Apple',))\n>               assert cursor.fetchone() is not None\n\ntest_db.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/abstracts.py:1621: in __exit__\n    self.close()\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py:495: in close\n    self._cnx.handle_unread_result()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mysql.connector.connection_cext.CMySQLConnection object at 0x1047739d0>, prepared = False\n\n    def handle_unread_result(self, prepared: bool = False) -> None:\n        \"\"\"Check whether there is an unread result\"\"\"\n        unread_result = self._unread_result if prepared is True else self.unread_result\n        if self.can_consume_results:\n            self.consume_results()\n        elif unread_result:\n>           raise InternalError(\"Unread result found\")\nE           mysql.connector.errors.InternalError: Unread result found\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:961: InternalError"}, "steps": [{"name": "Insert запрос в таблицу Manufacturer", "status": "passed", "start": 1698412599744, "stop": 1698412599745}, {"name": "Проверка добавления", "status": "passed", "start": 1698412599745, "stop": 1698412599746}], "start": 1698412599744, "stop": 1698412599746, "uuid": "d264e604-06ea-44a4-8199-dacf9346c0a9", "historyId": "b65128fb653106381ddce6c464717ae8", "testCaseId": "b65128fb653106381ddce6c464717ae8", "fullName": "test_db#test_insert_manufacturer", "labels": [{"name": "suite", "value": "test_db"}, {"name": "host", "value": "alexMBP-14.local"}, {"name": "thread", "value": "44581-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_db"}]}