{"name": "test_table", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.DatabaseError: 2014 (HY000): Commands out of sync; you can't run this command now", "trace": "self = <mysql.connector.connection_cext.CMySQLConnection object at 0x102474dc0>, query = b\"call Manufacturer_insert('Fake', 1)\", raw = False, buffered = False, raw_as_string = False\n\n    @with_context_propagation\n    def cmd_query(\n        self,\n        query: StrOrBytes,\n        raw: Optional[bool] = None,\n        buffered: bool = False,\n        raw_as_string: bool = False,\n    ) -> Optional[Union[CextEofPacketType, CextResultType]]:\n        \"\"\"Send a query to the MySQL server\"\"\"\n        self.handle_unread_result()\n        if raw is None:\n            raw = self._raw\n        try:\n            if not isinstance(query, bytes):\n                query = query.encode(\"utf-8\")\n>           self._cmysql.query(\n                query,\n                raw=raw,\n                buffered=buffered,\n                raw_as_string=raw_as_string,\n                query_attrs=self.query_attrs,\n            )\nE           _mysql_connector.MySQLInterfaceError: Commands out of sync; you can't run this command now\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:639: MySQLInterfaceError\n\nThe above exception was the direct cause of the following exception:\n\ndb_connection = <mysql.connector.connection_cext.CMySQLConnection object at 0x102474dc0>\n\n    @allure.story('Тестирование таблицы')\n    def test_table(db_connection):\n        with db_connection.cursor() as cursor:\n            with allure.step('INSERT в таблицу Manufacturer'):\n                cursor.execute('INSERT INTO manufacturer (name_manufacturer, country_id ) VALUES(\"Apple\", 1)')\n                db_connection.commit()\n                assert cursor.fetchone() is None\n    \n            with allure.step('Проверка результата INSERT'):\n                cursor.execute('SELECT * from manufacturer where name_manufacturer = %s', ('Apple',))\n                assert cursor.fetchone() is not None\n    \n            with allure.step('UPDATE в таблице Manufacturer'):\n                cursor.execute('UPDATE manufacturer SET country_id = %s WHERE name_manufacturer = %s', (2, 'Apple'))\n                db_connection.commit()\n                assert cursor.fetchone() is None\n    \n            with allure.step(\"Проверка результата UPDATE в таблице Manufacturer\"):\n                cursor.execute('SELECT country_id from manufacturer where name_manufacturer = %s', ('Apple',))\n                assert cursor.fetchone()[0] == 2\n    \n            with allure.step('DELETE из таблицы Manufacturer'):\n                cursor.execute('DELETE from manufacturer where name_manufacturer = %s', ('Apple',))\n    \n            with allure.step(\"Проверка результата DELETE в таблице Manufacturer\"):\n                cursor.execute('SELECT * from manufacturer where name_manufacturer = %s', ('Apple',))\n                assert cursor.fetchone() is None\n    \n            with allure.step('Проверка добавления данных через процедуру'):\n                cursor.execute(\"call Manufacturer_insert(%s, %s)\", ('Fake', 4))\n                assert cursor.fetchone() is not None\n    \n            with allure.step('Проверка целостности данных при добавлении данных через процедуру'):\n>               cursor.execute(\"call Manufacturer_insert(%s, %s)\", ('Fake', 1))\n\ntest_db.py:61: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py:330: in execute\n    result = self._cnx.cmd_query(\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/opentelemetry/context_propagation.py:77: in wrapper\n    return method(cnx, *args, **kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <mysql.connector.connection_cext.CMySQLConnection object at 0x102474dc0>, query = b\"call Manufacturer_insert('Fake', 1)\", raw = False, buffered = False, raw_as_string = False\n\n    @with_context_propagation\n    def cmd_query(\n        self,\n        query: StrOrBytes,\n        raw: Optional[bool] = None,\n        buffered: bool = False,\n        raw_as_string: bool = False,\n    ) -> Optional[Union[CextEofPacketType, CextResultType]]:\n        \"\"\"Send a query to the MySQL server\"\"\"\n        self.handle_unread_result()\n        if raw is None:\n            raw = self._raw\n        try:\n            if not isinstance(query, bytes):\n                query = query.encode(\"utf-8\")\n            self._cmysql.query(\n                query,\n                raw=raw,\n                buffered=buffered,\n                raw_as_string=raw_as_string,\n                query_attrs=self.query_attrs,\n            )\n        except MySQLInterfaceError as err:\n>           raise get_mysql_exception(\n                err.errno, msg=err.msg, sqlstate=err.sqlstate\n            ) from err\nE           mysql.connector.errors.DatabaseError: 2014 (HY000): Commands out of sync; you can't run this command now\n\n../../../../Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py:647: DatabaseError"}, "steps": [{"name": "INSERT в таблицу Manufacturer", "status": "passed", "start": 1698419096459, "stop": 1698419096461}, {"name": "Проверка результата INSERT", "status": "passed", "start": 1698419096461, "stop": 1698419096461}, {"name": "UPDATE в таблице Manufacturer", "status": "passed", "start": 1698419096461, "stop": 1698419096462}, {"name": "Проверка результата UPDATE в таблице Manufacturer", "status": "passed", "start": 1698419096462, "stop": 1698419096462}, {"name": "DELETE из таблицы Manufacturer", "status": "passed", "start": 1698419096462, "stop": 1698419096462}, {"name": "Проверка результата DELETE в таблице Manufacturer", "status": "passed", "start": 1698419096462, "stop": 1698419096463}, {"name": "Проверка добавления данных через процедуру", "status": "passed", "start": 1698419096463, "stop": 1698419096463}, {"name": "Проверка целостности данных при добавлении данных через процедуру", "status": "broken", "statusDetails": {"message": "mysql.connector.errors.DatabaseError: 2014 (HY000): Commands out of sync; you can't run this command now\n", "trace": "  File \"/Users/akopotov/Documents/College/Testing/checkpoint_6_dB_test/test_db.py\", line 61, in test_table\n    cursor.execute(\"call Manufacturer_insert(%s, %s)\", ('Fake', 1))\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/cursor_cext.py\", line 330, in execute\n    result = self._cnx.cmd_query(\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/opentelemetry/context_propagation.py\", line 77, in wrapper\n    return method(cnx, *args, **kwargs)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/mysql/connector/connection_cext.py\", line 647, in cmd_query\n    raise get_mysql_exception(\n"}, "start": 1698419096463, "stop": 1698419096463}], "start": 1698419096459, "stop": 1698419096467, "uuid": "adf1edad-cca3-4318-a4b3-0374dcd5b2eb", "historyId": "710907a623d0ec665d3ec0c1a744f881", "testCaseId": "710907a623d0ec665d3ec0c1a744f881", "fullName": "test_db#test_table", "labels": [{"name": "story", "value": "Тестирование таблицы"}, {"name": "suite", "value": "test_db"}, {"name": "host", "value": "alexMBP-14.local"}, {"name": "thread", "value": "45834-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_db"}]}