{"name": "test_api[item0]", "status": "passed", "steps": [{"name": "Get data", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/akopotov/Documents/College/Testing/checkpoint_5/base_request.py\", line 39, in get\n    response = self._request(url, 'GET', expected_error=expected_error)\n  File \"/Users/akopotov/Documents/College/Testing/checkpoint_5/base_request.py\", line 15, in _request\n    response = requests.get(url)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/requests/adapters.py\", line 486, in send\n    resp = conn.urlopen(\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py\", line 790, in urlopen\n    response = self._make_request(\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py\", line 467, in _make_request\n    self._validate_conn(conn)\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/urllib3/connectionpool.py\", line 1092, in _validate_conn\n    conn.connect()\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/urllib3/connection.py\", line 611, in connect\n    self.sock = sock = self._new_conn()\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/urllib3/connection.py\", line 203, in _new_conn\n    sock = connection.create_connection(\n  File \"/Users/akopotov/Library/Python/3.9/lib/python/site-packages/urllib3/util/connection.py\", line 73, in create_connection\n    sock.connect(sa)\n"}, "parameters": [{"name": "endpoint", "value": "'store/order'"}, {"name": "endpoint_id", "value": "'94'"}, {"name": "expected_error", "value": "False"}], "start": 1698336386278, "stop": 1698336398125}], "parameters": [{"name": "item", "value": "{'id': 94, 'petId': 102, 'quantity': 27, 'shipDate': '2018-1-25T16:16:15.827Z', 'status': 'postponed', 'complete': True}"}], "start": 1698336385740, "stop": 1698336398139, "uuid": "82aa36c3-3822-40b3-9100-c262cea8792c", "testCaseId": "6db8f7fc8632009bbecfa57e4460fc27", "fullName": "test_store#test_api"}